name: analyzer_plugin_proxy_generator
description: A plugin to proxy other analyzer plugins.
version: 0.0.1

homepage: https://github.com/spideythewebhead/analyzer_plugin_proxy_generator
repository: https://github.com/spideythewebhead/analyzer_plugin_proxy_generator
documentation: https://github.com/spideythewebhead/analyzer_plugin_proxy_generator
issue_tracker: https://github.com/spideythewebhead/analyzer_plugin_proxy_generator/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  file: ^6.0.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
